version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
    depends_on:
      - mongodb

  express-app:
    image: alexrandr/express-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      COIN_GUEKO_API_KEY: CG-Q1bJd5mxtq8WNGxEe1cRayem
      DB_URI: mongodb://admin:pass@mongodb:27017
      DB_HOST: mongo
      DB_PORT: 27017
      DB_USER: admin
      DB_PASS: pass
    depends_on:
      - mongodb
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=${WATCHTOWER_POLL_INTERVAL}
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  my_network:
