name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    #if: startsWith(github.event.head_commit.message, '[deploy]')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: tydaks
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: tydaks/express-app-image:latest
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: api.camille-lecoq.com
          username: tydaks
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd Count-of-money-API
            git pull origin main
            docker stack deploy -c docker-compose.yml countofmoney
