name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    branches: [ "cicd" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-push :
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker compose -f docker-compose.yml build
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: alexrandr
        password: dckr_pat_9N-4JJzl83fffaQQxjLxGttogzA
    - name: Docker Push GH Action
      run: docker compose -f docker-compose.yml push
